### ISSUE TITLE
debug logging not configurable

### ISSUE THREAD

**Issue by h0tw1r3** [voxpupuli/voxpupuli-acceptance#49]
Conflicting checks on how BEAKER_debug is determined to be enabled results in debug logging always enabled.

[beaker-rspec README](https://github.com/voxpupuli/beaker-rspec/blob/8ff37d13660909294db8e97937f2668cf37b0fd7/README.md?plain=1#L51) states:
> set to any value to enable beaker debug logging

But in this module the default is set to 'true' if unset. https://github.com/voxpupuli/voxpupuli-acceptance/blob/e1f5ad4eaedf10acc21b47c26045afe33c5c9c42/lib/voxpupuli/acceptance/spec_helper_acceptance.rb#L6

Unless I'm missing something obvious, there's no way to disable debug logging?

**Comment by ekohl** [comment]
You're right about the README, but since https://github.com/puppetlabs/beaker-rspec/commit/432dd337fa6f5ca231e89a959bae67e45b1b5b41 the actual code respects `no`. I've opened https://github.com/voxpupuli/beaker-rspec/pull/134 to document it.
